[theme]
base = "light"
primaryColor = "#1D4ED8"
backgroundColor = "#F0F6FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
